name = "Re-Pocket"
author = "2imeline"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92c2fdff8345f88e74521ac6f18a972158d4a2632285d77fe4f59c763b3ebb65"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
