name = "Re-Pocket"
author = "2imeline"
version = "0.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ef879c4943dc60f729e0d9080a6c6b0b5df53ac30d4892c77d6bc7cb2d2c75"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
